<script lang="ts">
  import { onMount } from "svelte";

  onMount(() => {
    var elems = document.querySelectorAll('.collapsible');
    var instances = M.Collapsible.init(elems, {});
  })
</script>

<div class="wrapper">
  <ul class="collapsible">
    <li>
      <div class="collapsible-header">Why is information theory important?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/d9alWZRzBWk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">How is random information generated by a physics engine?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/Ks1pw1X22y4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">What facts can we learn from observing said information?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/NfTmy1ApCvI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">Where in the real world does this phenomenon occur?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/a_BKQ_ZPImw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
  </ul>
</div>

<style>
  .wrapper {
    margin: 0;
    color: #333;
  }
</style>

