<script lang="ts">
  import { onMount } from "svelte";

  onMount(() => {
    var elems = document.querySelectorAll('.collapsible');
    var instances = M.Collapsible.init(elems, {});
  })
</script>

<div class="wrapper">
  <ul class="collapsible">
    <li>
      <div class="collapsible-header">Why is information theory important?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/d9alWZRzBWk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">How is random information generated by a physics engine?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/Ks1pw1X22y4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">What facts can we learn from observing said information?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/NfTmy1ApCvI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">Where in the real world does this phenomenon occur?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/a_BKQ_ZPImw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">When should we use entropy for perfect secrecy?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/FlIG3TvQCBQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">Who is allowed to communicate online securely?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/YEBfamv-_do" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">Once keys/settings are established how are they used to scramble messages?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/G2_Q9FoD-oQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">For each user in some member's list how are usernames/passwords kept?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/NuyzuNBFWxQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">If authorization is successful then how are abilities handled?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/cgTa7YnGfHA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">Which of the following DB paradigms is the safest for resource X?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/W2Z7fbCLSTw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">While members cooperate how do they reach consensus in leader elections?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/6xwMIYBp944" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
  </ul>
  <ul class="collapsible">
    <li>
      <div class="collapsible-header">Why is game theory important?</div>
      <div class="collapsible-body">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/7szPBZxBIg4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </li>
    <li>
      <div class="collapsible-header">Are the actors in this situation rational?</div>
      <div class="collapsible-body">
        <div>Leave your thoughts in the comment section down below.</div>
      </div>
    </li>
    <li>
      <div class="collapsible-header">Are we able to reach Nash Equalibrium?</div>
      <div class="collapsible-body">
        <div>Leave your thoughts in the comment section down below.</div>
      </div>
    </li>
    <li>
      <div class="collapsible-header">Do they act according to their self interest?</div>
      <div class="collapsible-body">
        <div>Leave your thoughts in the comment section down below.</div>
      </div>
    </li>
    <li>
      <div class="collapsible-header">Do they understand the rules of the game?</div>
      <div class="collapsible-body">
        <div>Leave your thoughts in the comment section down below.</div>
      </div>
    </li>
    <li>
      <div class="collapsible-header">Is their dominant strategy really that dominant?</div>
      <div class="collapsible-body">
        <div>Leave your thoughts in the comment section down below.</div>
      </div>
    </li>
  </ul>
</div>

<style>
  .wrapper {
    margin: 0;
    color: #333;
  }
</style>

